### ISSUE TITLE
Would be nice to have a discussion forum for Snap

### ISSUE THREAD

**Issue by haviital** [jmoenig/Snap--Build-Your-Own-Blocks#708] opened 2015-01-27 10:46 UTC
That would be useful for getting free form feedback, opinions and even compliments about your great tool :-) Have a link to it from your home page.

Maybe there is but I just have not found it (?).

**Comment by bb010g** [comment] 2015-02-01 21:20
Duplicate of #357.

**Comment by haviital** [comment] 2015-02-02 05:59
Ok, good. But please put a link to it in your home page.

**Closed** 2015-11-27 06:26 UTC
Labels: duplicate, website
