### ISSUE TITLE
Fill block causes crash

### ISSUE THREAD

**Issue by stezel** [jmoenig/Snap--Build-Your-Own-Blocks#1843] opened 2017-08-29 16:45 UTC
Here is an issue reported on Piazza with the "fill" block:
https://piazza.com/class/h8yx482idav52y?cid=1577

"Anyone else run into problems with using the "Fill" command? My students are doing the Abstract Art lab, U1L3, and many of them crash the program entirely when they try to fill in colors on the polygons. Is there a bug or workaround?"

I tried to replicate the crash and was able to do so when I tried to "fill" a region that was already filled with a color.  There might be something in the "fill" algorithm that goes into a loop when such a task is given.
Thank you for your help.
Selim

**Comment by micahcowan** [comment] 2017-08-29 18:55
I can confirm this, and also in **master** (though it took me more attempts to reproduce in the master branch than in the release - guessing it's related to what colors were chosen?)

**Comment by micahcowan** [comment] 2017-08-29 19:25
I had a difficult time finding a reliable way to reproduce, and basically stumbled on this one, which reliably crashes the browser tab if I run it in either the dev or release version of _Snap!_.

[Clicking this link may crash your browser tab](http://snap.berkeley.edu/snapsource/snap.html#present:Username=micahcowan&ProjectName=fill%20test%20CRASHES)

**Comment by cycomachead** [comment] 2017-08-29 19:52
This is fixed in the dev version I believe. @bromagosa, right?

/snapsource/dev/snap.html

**Comment by micahcowan** [comment] 2017-08-29 20:06
As I've said, it is _not_ fixed in the dev version. It is a continuing issue.

**Comment by jguille2** [comment] 2017-08-29 22:34
Hi @micahcowan ,

I think this is fixed for the next version with #1349 PR, but it is not yet merged into the dev branch.

In fact there are more 'blessed by Jens' PRs (some quite old) pending to merge into dev. Perhaps it is important to solve this to save us duplicate issues and because at the end (with the changes) their code will have to be revised again.
Thanks

Joan

**Comment by jmoenig** [comment] 2017-08-30 05:38
Interesting find. Thanks, @micahcowan , for the excellent and reliable way to reproduce this problem. So, it appears that the root of the issue is when you use  the fill tool with the *same* color. Hah! Great find, thank you so much!

**Comment by brianharvey** [comment] 2017-08-30 06:14
The correct behavior in that case is to do nothing at all.  So it could be special cased.

**Comment by bromagosa** [comment] 2017-08-30 06:39
IIRC, it is special cased in the paint editor, but maybe not in the fill
block.

Perhaps we could reuse the same code for both use cases?

**Comment by jmoenig** [comment] 2017-08-30 06:43
Yeah, that should work. But, thing is, the same-color check is already in the existing code, so I'm assuming the issue to be slightly different...

**Comment by jguille2** [comment] 2017-08-30 06:47
I'm sorry... now I see #1349 is not a PR... and of course it is not implemented... I'll investigate this but maybe the issue is fixed because other changes and the commit referenced...

Also I'll investigate if this change (about rounding integers) is the solution to this case.

Finally, I just only point that the issue is not always with the same color. In the @micahcowan project, if you repeat 'fill' with the first (red) color, there is not any problem. But with the two others (blue and green) the crash appears with the second 'fill'. This makes sense that the problem was in the calculation (again, JS subnormal numbers :( )

We follow this...

Joan

**Comment by jmoenig** [comment] 2017-08-30 06:52
found it!

**Comment by jmoenig** [comment] 2017-08-30 06:59
Oh no! Hmm...

**Comment by jmoenig** [comment] 2017-08-30 07:01
*Now* I see. This seems to be a *Color* issue. sometimes alpha is a fraction, and sometimes it's a byte. Geez.

**Comment by jmoenig** [comment] 2017-08-30 07:28
It's a *Morphic* issue: ```Morph.getPixelColor()``` doesn't transform the alpha-byte back to a fraction.

**Comment by jmoenig** [comment] 2017-08-30 07:50
Okay, *now* it's fixed. Please try the dev version: http://snap.berkeley.edu/snapsource/dev/snap.html
Thanks!

**Comment by jguille2** [comment] 2017-08-30 08:09
Yes @jmoenig, I can confirm is fixed in dev version. Thanks!

I don't know if I must return to the Color problems... (I have already forgotten almost everything about this :smile: )... Now I see I noted [this problems](https://github.com/jguille2/jguille2.github.io/blob/master/docs/progress.md#user-content-other-minor-changes-bug-fixes-details). In fact, other issues (for example with libraries that can put numeric values) made me use ['setters'](https://github.com/jguille2/Snap--Build-Your-Own-Blocks/blob/penColors/morphic.js#L1935-1957) to ensure that the values were always in the right intervals.

You will tell me if it is worth reopening the subject ... In any case, I would start from the beginning to check all the changes (which were many).

**Comment by jmoenig** [comment] 2017-08-30 08:29
Ah, wow, so you already noticed the exact cause of the bug a while ago!

**Comment by jguille2** [comment] 2017-08-30 08:39
Yes... but I forgot too :smile:
Our dear **abstraccion** :star2:... makes it necessary to close subjects in a not so long time...

**Closed** 2017-09-01 10:09 UTC
Labels: bug, fixed in next version, paint editor
