### ISSUE TITLE
Contains Block Error

### ISSUE THREAD

**Issue by lmock** [jmoenig/Snap--Build-Your-Own-Blocks#758] opened 2015-04-02 07:40 UTC
So we ran into an interesting bug with a student's homework assignment in which he uses the contains block. For him, passing a booleon into the contains block actually DID work, but ONLY on his computer. When we tried running his homework on other computers, the block errored out. Here's an example of what we saw on our end (i.e. the block not working). Jens, I'll email you the student's file because I can't post it publicly (because if I did, I'd be releasing a HW solution!).

![error](https://cloud.githubusercontent.com/assets/5467107/6959485/74d8b952-d8ce-11e4-8200-6f9df10525a9.JPG)

Thanks! :)

@cycomachead because Michael's also familiar with what happened.

**Comment by jmoenig** [comment] 2015-04-02 11:02
Okay, I can reproduce the error you're showing here (and it is supposed to be an error, I think), but I cannot reproduce how the project you've sent me could ever have worked...

**Comment by cycomachead** [comment] 2015-04-02 11:34
[Responded via email, but for the sake of clarity for everyone else, and in case I'm wrong someone can correct me....]

This shown is the correct behavoir, but not what happens in the student project.

What I _suspect_ is this:
String.prototype.contains is defined in newer (some) newer browsers. FF on the Mac has the function already. The contains block does indeed work on strings.
![index](https://cloud.githubusercontent.com/assets/1505907/6963219/659ca4d0-d8f1-11e4-8fc7-2116305577bd.png)


In a current (non-FF) browser console, define:
String.prototype.contains = function (item) { return this.indexOf(item) != -1; }
and it should work as the student had it happen.

**Comment by jmoenig** [comment] 2015-04-02 11:57
Yes, I got the email, and you're absolutely right, Michael! I just updated my FF and it did run the project without throwing an exception, because in that JS version, the String prototype understands contains(substr).

So, roping @brianharvey into this discussion, should be *disable* "contains" for strings (because it is list-colored). Personally I think it's okay to leave it as-is and enjoy the additional functionality :-)

Thanks, Michael, for finding the reason for this!

**Comment by brianharvey** [comment] 2015-04-02 11:58
On 4/2/15 4:57 AM, Jens Mönig wrote:
> So, roping @brianharvey into this discussion, should be*disable*  "contains" for strings (because it is list-colored). Personally I think it's okay to leave it as-is and enjoy the additional functionality:-)

That's fine with me!

**Comment by cycomachead** [comment] 2015-04-02 19:47
So, I don't think contains working on strings is bad, but what does concern me is that right now this can break compatibility between browsers and users. (Of course, it's technically "programmer error" since the types don't line up, but students likely won't realize that. Especially in the case of this project where "combine" was used and both blocks are red.)

**Comment by cycomachead** [comment] 2015-07-09 07:16
@jmoenig 

Ok, so I was doing some more research on this issue --

It turns out `String.prototype.contains` was never a finished spec. FF40 (next update, IIRC), and Chrome 40x renamed the contains function to be `includes` so we'll go back to Snap<i>!</i> bubbling up a JS error in this case.

**Comment by cycomachead** [comment] 2015-11-17 12:27
Closing this, because some day the error handling in all the list primitives will be sorted out. ;-)

**Closed by cycomachead** 2015-11-17 12:27 UTC
Labels: browser-specific, error handling
