### ISSUE TITLE
Embedding Snap app in web page

### ISSUE THREAD

**Issue by katherinebernstein** [jmoenig/Snap--Build-Your-Own-Blocks#719] opened 2015-02-08 23:31 UTC
Is there a way to embed an app build using Snap in a web page?

**Comment by cycomachead** [comment] 2015-02-08 23:36
There isn't a way that's exactly like Scratch (not at the moment).
However, usually projects just `iframe` the Snap! Application.
```html
<iframe src="//snap.berkeley.edu/snapsource/snap.html#present:Username=User&ProjectName=project" width="XXX" height="YYY"></iframe>
```

You can get the URL for a shared project from the URL bar when you open it. However, you should remove the `http:` from the URL when embedding the iframe into a page.

**Comment by jmoenig** [comment] 2015-02-09 08:08
Ugh, iFrames work, of course, but that's not really embedding Snap projects into a web page. When I created Morphic.js I made sure you *can* run several independent Morphic worlds on a single web page without using an iFrame. There is a section on how to accomplish this in the Morphic documentation, and I've also posted an example here:

http://snap.berkeley.edu/snapsource/multiple.html

In the same way you should be able to set up multiple Snap projects on a single web page, and you should be able to write a script that does the embedding for you. This would be a nice student project, or a nice open-source contribution!

**Comment by cycomachead** [comment] 2015-02-09 08:41
I actually might get to it this semester...

Though in my initial experience embedding a partial view of Snap<i>!</i> in an existing web page required a bit of modification...not sure what the cause of that was.

**Comment by jmoenig** [comment] 2015-02-09 10:46
Excellent, @cycomachead . I wouldn't be surprised if we find some issues once you try that, but I'm confident those are solvable.

Simply presenting multiple playable projects on a single page should be pretty straightforward, limited only by the hardware/browser configuration, because all those "worlds" are going to share the page's steps (ticks), which possibly slows each of them down by the number of total worlds on the page.

Switching to edit mode could be allowed depending on the presentation space's extent (there's a minimum extent for edit mode - you'll find it in the code somewhere) or disabled, or it could open another dedicated tab for editing the project.

All in all it can't be hard :-)

**Comment by danielzfranklin** [comment] 2015-04-20 16:08
Has any progress been made on this?
I am trying to make a written version of Scratch that evaluates to Snap! XML, so if this worked I embed it in the editor that  I am designing.

Snap! looks incredible, thanks for all of your work on it,
Daniel

**Comment by jmoenig** [comment] 2015-04-20 17:34
Oh yes, there's a pending pull request from Bernat, which I'll pull later this week!

Von meinem iPhone gesendet

**Comment by Geocali** [comment] 2018-07-04 09:18
Hello @cycomachead , @jmoenig !
Did you succeed to embed a Snap! project in a web page ?

**Comment by Geocali** [comment] 2018-07-04 11:33
Great, thanks !

**Comment by cycomachead** [comment] 2018-07-04 12:06
Closing since I think the original issue was solved. :)

**Closed by cycomachead** 2018-07-04 12:06 UTC
