### ISSUE TITLE
Exception while deleting a block

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#1798] opened 2017-07-11 10:18 UTC
About 1/5th of the time when deleting a block and clicking 'yes' the dialog stays up. Console shows

Uncaught TypeError: Cannot read property 'stop' of null
    at CustomCommandBlockMorph.BlockMorph.destroy (blocks.js:3829)
    at CustomCommandBlockMorph.BlockMorph.deleteBlock (blocks.js:2672)
    at objects.js:4553
    at Array.forEach (<anonymous>)
    at SpriteMorph.deleteAllBlockInstances (objects.js:4552)
    at CustomCommandBlockMorph.<anonymous> (byob.js:934)
    at DialogBoxMorph.accept (widgets.js:2272)
    at DialogBoxMorph.ok (widgets.js:2314)
    at PushButtonMorph.TriggerMorph.trigger (morphic.js:9293)
    at PushButtonMorph.TriggerMorph.mouseClickLeft (morphic.js:9354)
BlockMorph.destroy @ blocks.js:3829
BlockMorph.deleteBlock @ blocks.js:2672
(anonymous) @ objects.js:4553
SpriteMorph.deleteAllBlockInstances @ objects.js:4552
(anonymous) @ byob.js:934
DialogBoxMorph.accept @ widgets.js:2272
DialogBoxMorph.ok @ widgets.js:2314
TriggerMorph.trigger @ morphic.js:9293
TriggerMorph.mouseClickLeft @ morphic.js:9354
PushButtonMorph.mouseClickLeft @ widgets.js:194
Morph.escalateEvent @ morphic.js:4351
StringMorph.mouseClickLeft @ morphic.js:8479
HandMorph.processMouseUp @ morphic.js:10805
(anonymous) @ morphic.js:11455

**Comment by jmoenig** [comment] 2017-07-11 10:23
Can you help me reproduce this error? Are you deleting a single block instance or a custom block definition? Also, can you perhaps share the project that exhibits this behavior (or send it to me privately via email if you don't like sharing it here)?

Thanks!

**Comment by ToonTalk** [comment] 2017-07-11 10:54
It was a custom block definition in 
https://snap.berkeley.edu/snapsource/snap.html#present:Username=toontalk&ProjectName=command

When I clicked on 'No' after the error with 'Yes' all seemed fine and the block was gone. The block I was deleting differed from another block only in the colour category and the capitalisation of the first letter in its 'name'. I'm pretty sure there were no longer any instances using the block definition being deleted.

**Comment by ToonTalk** [comment] 2017-07-11 11:47
It occurred in another project.
[command broadcast 4.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/1138732/command.broadcast.4.zip)

Deleting the gray "Listen and then ..." triggers this.

**Comment by ToonTalk** [comment] 2017-07-11 11:49
I meant "listen and then ..." -- there is a similar command in Sensing that start with a capital L.

**Comment by jmoenig** [comment] 2017-07-11 12:36
Thanks, I can reproduce it with this project!
Investigating....

**Comment by jmoenig** [comment] 2017-07-11 12:40
Okay, first, the good news: Whatever is causing this error seems to be resolved in the upcoming release:

http://snap.berkeley.edu/snapsource/dev/snap.html

When I open your project in the dev version and delete the block definition, the same error that occurs in the current one doesn't happen, and everything seems to work fine.

Now, let me find out why this is happening...

**Comment by jmoenig** [comment] 2017-07-11 12:48
Seems to be a silly bug in my old code. In line 

https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/blocks.js#L3827

there's a set of parentheses missing.

Since this method has been completely redone in the upcoming version to avoid this bug, I'm not going to fix it before the release. I hope that's okay with you. (You're very welcome to test the dev version, btw!)

**Comment by ToonTalk** [comment] 2017-07-11 14:17
It is easy to work around this bug so no need to fix it before the next release. 

I might play with the dev version. Where are the difference documented?

**Comment by jmoenig** [comment] 2017-07-11 14:25
Thanks, Ken! It's great that you can work around this bug until the next release. It's also wonderful if you're willing to test the dev version. It's *supposed* to be quite stable now. I've yet got to document the changes in detail. the biggest new feature is full prototypal OOP. Here's a short overview of the current state:

Features:
* polymorphic sprite-local custom blocks
* inheritance of sprite-local custom blocks
* inheritance of sprite attributes (x, y, direction, size, costumes, costume #, sounds, scripts)
* first-class costumes and sounds
* localization support when typing expressions
* support for user-forced line-breaks in custom block labels
* ternary Boolean slot setting: support to limit Boolean input slots to “true/false” outside of rings and in palette
* support for default values in custom block Boolean slots
* experimental: duplicate block definition (hidden in shift-click context menu)
* support for codification of String, Number and Boolean value types
* costume icons indicate svg costumes
* sprites’s rotation centers can be adjusted onstage
* clones share their original sprite’s scripts, not a shallow-copy of them
* a highlight-colored balloon indicates the number of active processes per shared script
* new musical “notes” symbol
* turn on the “Inheritance support” setting per default
* Assert data types to list operations for more meaningful error messages

Fixes:
* changed keyboard shortcut indicator for “find blocks” to “^”
* prevent Snap from “hanging” when encountering certain errors in visible stepping 
* only mark implicit parameters if no formal ones exist
* optimized thread-launch and script highlighting to a single frame instead of formerly two
* changed direction attribute of sprites to automatically confine to 0-360 degrees
* fixed some typos

**Closed** 2017-07-13 19:22 UTC
Labels: fixed in next version
