### ISSUE TITLE
Forbidden to  access snap

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap--Build-Your-Own-Blocks#1120] opened 2016-01-28 16:55 UTC
Today I am getting the following "forbidden" message when I try to use this url:
http://snap.berkeley.edu/

Forbidden

You don't have permission to access / on this server.

I get it from our university computers and from my verizon phone with wifi turned off.

Yesterday, I got to snap from my home pc just fine.

thanks for whatever you can do,
Jerry

![image](https://cloud.githubusercontent.com/assets/5361659/12651646/07bfbb8c-c5ad-11e5-8d2e-8dc2a2f21500.png)

**Comment by liam4** [comment] 2016-01-28 17:21
Duplicate of #1119.

**Comment by cycomachead** [comment] 2016-01-28 19:07
It should be backup.

**Closed by cycomachead** 2016-01-28 19:07 UTC

**Comment by jcaldw737** [comment] 2016-01-28 21:10
Thank you very much for the prompt fix!
