### ISSUE TITLE
optimization problem with block library loading.

### ISSUE THREAD

**Issue by MelonCode** [jmoenig/Snap--Build-Your-Own-Blocks#1466] opened 2016-10-20 20:08 UTC
When you're trying to open Snap with tool blocks preloaded, or load custom stuff from XML files in other ways it completely freezes a tab or even a whole browser. 

The simplest way to reproduce the issue is to open this link in Firefox browser 
http://snap.berkeley.edu/init

Issue was noticed on 4 different devices (2 PCs and 2 Macbooks), and happens mostly in browsers that don't use V8 JavaScript Engine (Not chromium based) browsers (Safari, Firefox). 
In Google Chrome it's ok currently, but in other browsers no.

**Comment by brianharvey** [comment] 2016-10-20 20:41
Hmm, it works for me.  Takes a few seconds in Firefox, but not long enough for a spinning beachball, let alone an "unresponsive script" dialog.

The specific case of the tools should be solved fairly soon because we're working on making them real primitives.  But I'm leaving this open (with a changed title) with respect to the general issue of importing libraries.

**Comment by cycomachead** [comment] 2016-10-20 23:40
#363 #1194 

This has happened for a while, in various cases. There should be more issues, but I can't find them right now.

Anyway, there's twp problems:
* library files aren't loadly in an async matter which blocks execution
* improving performance of block loading has long been asked for.

Firefox specifically has the scripts problem, and there's is an `about:config` setting for improving performance in FF, but this is a general problem.

**Comment by cycomachead** [comment] 2018-08-07 10:34
Duplicate of #296 

(essentially, should have tagged that long ago.)

**Closed by cycomachead** 2018-08-07 10:34 UTC
Labels: browser-specific, enhancement, tools / libraries
