### ISSUE TITLE
A (possible?) bug with the call block.

### ISSUE THREAD

**Issue by BookOwl** [jmoenig/Snap--Build-Your-Own-Blocks#1861] opened 2017-09-13 19:25 UTC
See http://snap.berkeley.edu/snapsource/snap.html#present:Username=bookowl&ProjectName=Bug%20report

**Comment by TheAspiringHacker** [comment] 2017-09-13 22:17
I'm trying to trace the error:
1. The error is thrown from [`VariableFrame.prototype.find`](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/ba9a7bd6f6c3278945a829be694ab42bf1555353/threads.js#L3923). The function obviously tried to find a variable called "arguments" that is presumably built into the internal function code.
2. The name "arguments" appears as as a key in [thread.js](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/ba9a7bd6f6c3278945a829be694ab42bf1555353/threads.js#L1002)
[A comment reads that the `parameterID` `['arguments']` is used for varargs.](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/threads.js#L1115) BookOwl's project uses varargs. The code with the "arguments" key involve iteration over `allEmptySlots`, and BookOwl's project uses empty slots. Coincidence? I think NOT! Perhaps some slots are not counted as empty, and therefore don't have `['arguments']`?
3. [`allEmptySlots` is defined here.](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/ba9a7bd6f6c3278945a829be694ab42bf1555353/blocks.js#L370) It calls `isEmptySlot`.
4. [`ArgMorph` is used for list icons.](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/17ca9a3a62fc6ab78af5e5df9e4436d916ce6898/blocks.js#L6737) [It defines `isEmptySlot` like this.](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/17ca9a3a62fc6ab78af5e5df9e4436d916ce6898/blocks.js#L6877) Thus, when BookOwl's code with the list icon is executed, it works.
[`MultiArgMorph` is used for varargs.](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/17ca9a3a62fc6ab78af5e5df9e4436d916ce6898/blocks.js#L10029) [This is its definition of `isEmptySlot`.](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/ba9a7bd6f6c3278945a829be694ab42bf1555353/blocks.js#L10461) The function can only return `true` if `canBeEmpty` is `true`. `canBeEmpty` is set to `false` in several places: [Line 835](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/ba9a7bd6f6c3278945a829be694ab42bf1555353/blocks.js#L835), [Line 839](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/ba9a7bd6f6c3278945a829be694ab42bf1555353/blocks.js#L839), [Line 843](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/ba9a7bd6f6c3278945a829be694ab42bf1555353/blocks.js#L843), and [Line 886](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/ba9a7bd6f6c3278945a829be694ab42bf1555353/blocks.js#L886)

I assume that some code expects `canBeEmpty` to be `true` when it is actually `false`. I'm struggling to find which case applies to BookOwl's project because I'm not familiar with the codebase or internal script representation. So, I'm stuck.

**Comment by Jonathan50** [comment] 2017-09-14 03:04
I think this is at #1245

**Comment by cycomachead** [comment] 2017-09-14 05:59
Duplicate of #1245

**Closed** 2017-09-14 12:19 UTC

**Comment by BookOwl** [comment] 2017-09-14 13:02
Following @jmoenig's advice in the other thread I tried 
![index](https://user-images.githubusercontent.com/13385064/30431035-427402d0-992b-11e7-96b4-750241b7028a.png)
and it still errors out on me.
How can I work around this "feature"?

**Comment by Jonathan50** [comment] 2017-09-15 04:24
Can you remove the parameter #1 and try again?
