### ISSUE TITLE
go to back block

### ISSUE THREAD

**Issue by brollb** [jmoenig/Snap--Build-Your-Own-Blocks#1207] opened 2016-05-05 16:11 UTC
There is a `go to front` block but no `go to back` block; if someone tries to emulate a `go to back` block using the `move back ___ layers` w/ a large number, the block will nop if the number of layers is too high.

A simple fix could be to have the `move back ___ layers` block move back `Math.min(totalLayers, requestedLayers)` rather than ignoring requests with a request higher than the total number of layers

**Comment by brianharvey** [comment] 2016-05-05 20:30
+1.  That works in Scratch.

**Comment by cycomachead** [comment] 2016-05-06 20:26
Side note - this is a duplicate of #1089 ?

**Comment by brollb** [comment] 2016-08-26 19:43
I didn't see #1089 when I first made this but I think they might be different; I am not sure if #1089 is requesting the drop down fix or different behavior when given a larger number of layers. Initially, it sounds the same as this one but then I wasn't sure if the suggestion about the drop down was going to be the requested solution...

Anyway, I left this one open in case the drop down was still going to be used; if so, then #1089 would be the issue for it. If not, then this issue is certainly a duplicate

**Comment by cycomachead** [comment] 2016-08-26 19:52
True...I think fixing the bug is enough, though i guess the menu option doesn't hurt..but it's not breaking anything.

**Closed** 2017-01-09 16:56 UTC
Labels: cat: looks, duplicate, enhancement, Scratch Compatibility
