### ISSUE TITLE
Relabel only includes subexpressions in some menu options

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1143] opened 2016-02-22 18:47 UTC
![image](https://cloud.githubusercontent.com/assets/6549787/13228580/c5f6cca0-d96a-11e5-95b4-3db17c3b598b.png)

**Comment by jmoenig** [comment] 2016-02-22 19:36
Can you share the project? I'd like to investigate. Thanks!

**Comment by maryfries** [comment] 2016-02-22 20:10
http://snap.berkeley.edu/snapsource/snap.html#present:Username=mfries&ProjectName=U6L1-Tree

**Comment by jmoenig** [comment] 2016-02-22 22:18
Thanks! This is a regression bug that's been around for a surprisingly long time, ever since we changed the Morphic duplication mechanism last summer. I've been able to track it down and fix it in my dev version. I will push it along with the table feature in v4.0.5 real soon now.

**Comment by jmoenig** [comment] 2016-02-22 22:22
... Please check out the fix in the dev version:

http://snap.berkeley.edu/snapsource/dev/snap.html#present:Username=mfries&ProjectName=U6L1-Tree&editMode

(if it doesn't work right away make sure to clear your cache).
Again thanks for catching this longstanding bug!

**Comment by maryfries** [comment] 2016-02-22 22:28
works!! :)

**Comment by jmoenig** [comment] 2016-02-22 22:33
Thanks for the quick testing, Mary!

**Comment by cycomachead** [comment] 2016-02-23 00:19
Thanks! I've been meaning to file this one for a while...

**Comment by jmoenig** [comment] 2016-02-24 11:27
fixed with df0269f5ccfce06e3c577aadb5b3559263edb9b2

**Closed by jmoenig** 2016-02-24 11:27 UTC
Labels: bug, fixed in next version, regression

**Comment by maryfries** [comment] 2016-03-01 01:13
Reopening because this is what I'm getting now—Overzealous relabeling:

![image](https://cloud.githubusercontent.com/assets/6549787/13414397/8bf54520-df20-11e5-9277-e91d8f754032.png)

If this is functioning as intended, please feel free to close again, but there are way more options here than I would expect most people to want. How are these being determined for custom blocks?

**Comment by jmoenig** [comment] 2016-03-01 07:57
Oh well. I hate when this happens.

This "overzealous" looking for alternatives is actually intentional. Well, not quite. At first I only showed other custom blocks that shared the same type (command or reporter), the same category (Motion, Pen, etc.) and the same number - and even types - of inputs. Then users started discovering the relable feature and began asking for more and more alternatives. So now we have a select few alternatives for primitives, but for custom blocks I'm showing every other custom block of the same type (command or reporter), regardless of its category or inputs. I agree with you that this is very, very broad, probably too broad for beginners, but it's really the result of giving in to user requests.

I invented "morphing" blocks into others in place so I didn't have to pluck big scripts apart just to exchange a "BROADCAST" block into "BROADCAST AND WAIT" (which still is by far the most common cause for relabelling for myself). Then users began to love this feature "too much", and before you know it "scope creep" occurs. Same with "zoom blocks" (originally just an option to let Dan print out higher-res posters for his class) and the checkmark boxes in the "export blocks" dialog. These features start to develop a life of their own...

**Comment by jmoenig** [comment] 2016-03-01 07:59
So, just to make this clear, this isn't a new behavior, it's been there for a couple of years, even. So, maybe we could turn it into a new issue?

**Comment by cycomachead** [comment] 2016-03-01 08:43
> This "overzealous" looking for alternatives is actually intentional. Well, not quite. At first I only showed other custom blocks that shared the same type (command or reporter), the same category (Motion, Pen, etc.) and the same number - and even types - of inputs. Then users started discovering the relable feature and began asking for more and more alternatives.

I think we should probably discuss / outline a default plan and then stick to it. I think the version I would write, if I were to implement this would match:
* number of inputs
* block 'replacability' (commands only replace commands, but reporters can replace predicates)

I explictly wouldn't check for two things:
* the category
* whether the input types match

In my view, this leaves out a few potentially useful relabelings such as `if` → `if-else`, and could show a few too many things such as allowing `-` to be relabeled to `and`. However, it would mean every relabel is bi-directional, without popping code out, and given that Snap! is dynamically typed, the code would still be 'syntactially' correct. (can we use that word for a blocks langauge? Hmm...) 

> So, maybe we could turn it into a new issue?

Eh, this one is fine. We can edit the title.

**Comment by brianharvey** [comment] 2016-03-02 04:37
You'll hate this idea, I'm betting, but here's what I'd do:  Have a target of, say, five blocks.  Start with the most restrictive possible rule: Same color, same number of inputs, 50% similar (on some measure) title text.  So that would choose only the blocks with "triangle" in the name, maybe.

If you have fewer than 5, relax a rule.  Keep doing that until either you have all custom blocks or the menu is bigger than 5.

If you reached 5 and there are still excluded candidates, put a "see more blocks" option at the bottom, which re-runs the algorithm with a limit of 10, then 15, etc.

P.S.  For this purpose, we should consider treating blocks from libraries as pseudo-primitives.
