### ISSUE TITLE
"play note for beats" block is failing on Chrome: createGain is not a function

### ISSUE THREAD

**Issue by ptorr-msft** [jmoenig/Snap--Build-Your-Own-Blocks#1615] opened 2017-01-13 17:40 UTC
One of my students is hitting issues with the `play note` feature failing on Chrome. 

The error is `Type Error Note.prototype.audioContext.createGain is not a function` when using the block in a new SNAP! project. He has tried two different computers and both fail the same way. 

The Chrome version is `55.0.2883.87 m`

**Comment by micahcowan** [comment] 2017-01-13 19:55
Hello! I'm not a dev, just someone who likes to read the issue reports :)

My understanding is that this is a known issue, and it is fixed in the version under development. The project's developer, @jmoenig, is in the process of making a new release of _Snap!_ specifically to address this exact issue, after which point the issue should be solved for you.

One workaround is to use an older version of Chrome than 55. :/

**Comment by liam4** [comment] 2017-01-13 20:03
Yeah, this is a duplicate of this issue, which you might find useful: #1543

**Comment by ptorr-msft** [comment] 2017-01-13 20:10
Thank you!

**Closed** 2017-01-13 20:18 UTC

**Comment by jmoenig** [comment] 2017-01-14 17:09
the release that fixes this issue will be deployed tomorrow! :-)
