### ISSUE TITLE
Deleting custom block definition creates extra input box, causing other bugs

### ISSUE THREAD

**Issue by snorthway** [jmoenig/Snap--Build-Your-Own-Blocks#1553] opened 2016-12-08 16:21 UTC
Related in some way to #1372 but I didn't see anything about an extra input box in that discussion. Apologies if I missed something there that makes this a duplicate.

Steps:

1. Make a normal script
<img width="120" alt="screen shot 2016-12-08 at 11 05 50 am" src="https://cloud.githubusercontent.com/assets/2825499/21017323/ff5cdad8-bd36-11e6-8038-e0d839bed529.png">

2. Create a custom block (note that this works regardless of whether there's any code in the custom block)
<img width="573" alt="screen shot 2016-12-08 at 11 06 10 am" src="https://cloud.githubusercontent.com/assets/2825499/21017357/16f45450-bd37-11e6-8ac0-a988ec2a0a9f.png">
<img width="615" alt="screen shot 2016-12-08 at 11 06 19 am" src="https://cloud.githubusercontent.com/assets/2825499/21017359/1954d7ba-bd37-11e6-8a6d-ee3dc9748996.png">

3. Put the custom block at the end of your script
<img width="135" alt="screen shot 2016-12-08 at 11 06 28 am" src="https://cloud.githubusercontent.com/assets/2825499/21017371/24de4e04-bd37-11e6-93d4-86b763f5d416.png">

4. Right click the block you just put in and select "delete block definition"
<img width="550" alt="screen shot 2016-12-08 at 11 06 38 am" src="https://cloud.githubusercontent.com/assets/2825499/21017385/30776340-bd37-11e6-89f0-38d068bd2d74.png">

5. An extra input box appears at the end of the last block.
<img width="123" alt="screen shot 2016-12-08 at 11 06 42 am" src="https://cloud.githubusercontent.com/assets/2825499/21017400/35ac3430-bd37-11e6-8c0d-c7d76947ca61.png">
<img width="145" alt="screen shot 2016-12-08 at 11 06 53 am" src="https://cloud.githubusercontent.com/assets/2825499/21017426/4a98cc1e-bd37-11e6-9729-3d5badabbbe8.png">

6. BONUS: if you put a block inside the extra input box, you ~rip a hole in the space-time continuum~ can see a few other bugs.

For example, I accidentally dragged a "pick random" into the box. When trying to remove it, it just made this huge shadow.
<img width="360" alt="screen shot 2016-12-08 at 11 08 58 am" src="https://cloud.githubusercontent.com/assets/2825499/21017457/6d0634b2-bd37-11e6-9e7f-f63bf8eace57.png">

When I ran it and turned on visible stepping, this happened:
<img width="611" alt="screen shot 2016-12-08 at 11 09 37 am" src="https://cloud.githubusercontent.com/assets/2825499/21017491/8ea82c10-bd37-11e6-848e-84efca26ed3e.png">

**Comment by maryfries** [comment] 2016-12-08 18:06
Wow! You also seem to have acquired an extra input slot in your SAY block.

I played around with this some more, and it seems that the shadow stays with the block even if the block is resized or moved.

![image](https://cloud.githubusercontent.com/assets/6549787/21021568/0d674d38-bd47-11e6-9037-864d10192978.png)

**Comment by snorthway** [comment] 2016-12-08 21:21
To be clear, the extra input on the "say" block was the result of a similar test. 

I also couldn't get the block with the shadow to move at all.

**Comment by maryfries** [comment] 2016-12-08 22:11
I had to oust the block with the shadow by dropping another block in the same extraneous slot.

**Comment by jguille2** [comment] 2016-12-08 23:41
Yes!
The bug is in the extra input created for the deleting action.
I've seen the problem is origin in [this change](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/commit/ff5f9a7601d1b37868ab6ccc5b79fd9b78362411#diff-5f5bb19933ecde89bb86b19173cdef9eL2531) made in October to improve Visible stepping feature.

I think the problem is the related change should only affect to reporter blocks.

I'll push a PR to make the work easier (I've tested and it fix the problem) but @jmoenig will see if it is the right change.

**Comment by snorthway** [comment] 2016-12-09 03:34
Thanks for the prompt response and PR!

**Comment by jmoenig** [comment] 2016-12-09 07:45
Thank you, @snorthway , for this excellent catch and very reproducible bug description!

**Comment by jmoenig** [comment] 2016-12-09 07:46
closing this issue, because @jguille2 has fixed it with his PR which I've just now pulled. this will be in the next minor release (coming up around Christmas)

**Closed by jmoenig** 2016-12-09 07:46 UTC
