### ISSUE TITLE
Exporting blocks should include dependencies

### ISSUE THREAD

**Issue by kephas** [jmoenig/Snap--Build-Your-Own-Blocks#2143] opened 2018-07-06 03:19 UTC
I exported a drawing library I created to help kids make complicated procedural drawings, but apparentely forgot one block I used from the list utilities in there. I shouldn't have to manually keep track of every block I use to be able to export the blocks I created, this defeats the whole purpose of abstraction…

**Comment by brianharvey** [comment] 2018-07-06 06:44
Yes, this is a known problem.

**Comment by jmoenig** [comment] 2018-07-06 06:48
In the meantime, here's how I always do it myself:

1. export *all* custom blocks from the source project and import them *all* into the target project
2. after you're done with the target project select "Unused blocks..." in the project menu and remove all unused blocks from the projects, to make it small and snazzy to load.

"Unused blocks" keeps track of all dependencies and also catches indirect ones.

**Comment by kephas** [comment] 2018-07-06 11:21
Yes, I realized I can do the export I want by first pruning unused blocks with all my wanted blocks deselected. But if the logic of dependency checking is in there, it shouldn't be too hard to have the reverse UI.

**Comment by cycomachead** [comment] 2018-08-07 08:10
Duplicate of #1126

**Closed by cycomachead** 2018-08-07 08:10 UTC
Labels: enhancement
