### ISSUE TITLE
Say command truncates URL

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#1776] opened 2017-06-27 14:57 UTC
![image](https://user-images.githubusercontent.com/2138696/27594257-3acf49b2-5b51-11e7-876b-fc71526cdcfd.png)

Windows 10 Chrome

**Comment by brianharvey** [comment] 2017-06-27 15:23
Nothing special about URLs; SAY truncates any long text.  This behavior is inherited from Scratch and therefore it may be hard to convince Jens to fix it, but given the precedent of SAYing lists that include scroll bars, maybe we could have a horizontal scroll bar when SAYing a long text without spaces.

**Comment by cycomachead** [comment] 2017-09-18 04:05
Duplicate of #109

**Closed** 2018-07-21 07:03 UTC
Labels: IDE, cat: looks, misfeature
