### ISSUE TITLE
Program Code Missing

### ISSUE THREAD

**Issue by nlentino223** [jmoenig/Snap--Build-Your-Own-Blocks#1739] opened 2017-04-28 16:45 UTC
A student created a program, they saved the file, went to open the file today and the code they wrote is gone; but the three variables they created are in the variables palette, as well as, two of three custom blocks.

This is for the AP CSP performance task due this weekend.  Is there any way to get the code back?

**Comment by SBISHOV** [comment] 2017-04-29 17:38
Same thing happened to my student yesterday (4/28).  I tried a workaround suggested  by the BJC Piazza discussion group, no luck.  The only thing left for my student was a few variables and parts of scripts for five sprites.

**Comment by jguille2** [comment] 2017-04-29 22:19
Hi @nlentino223 and @SBISHOV,

My hypothesis (you have stored in the cloud only a piece of work) is that the cause is a disconnection (problems with your internet connection or a connection to SnapCloud server).
Then, after the disconnection, your students were saving their work into the LocalStorage.

If they have the option to use the same computer (same user, same browser ... and trusting it is not frozen or reset), they'll find the projects ins the LocalStorage, with the same name.

Joan

**Comment by SBISHOV** [comment] 2017-04-30 01:48
Thank you Joan, will get the student to check this idea.
Sheldon

**Comment by SBISHOV** [comment] 2017-04-30 06:10
Unfortunately  for this student  the project was not in browser storage.  Other thoughts appreciated, meanwhile will suggest that the student recreate as much as possible.

**Comment by maryfries** [comment] 2017-05-01 20:25
See also: 
https://piazza.com/class/i7hy3udaukx6su?cid=391
https://piazza.com/class/h8yx482idav52y?cid=1412

**Comment by maryfries** [comment] 2017-05-01 20:27
Nicole, have you seen this response on Piazza? "If you are seeing variables but not scripts, most likely you have selected the wrong sprite, or the stage, in the sprite corral.  Try choosing the sprite where you made the scripts."

**Comment by cycomachead** [comment] 2018-07-21 07:06
Closing because this would have been related to the old cloud system.

**Closed by cycomachead** 2018-07-21 07:06 UTC
Labels: cloud
