### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by jh69243** [jmoenig/Snap--Build-Your-Own-Blocks#1835] opened 2017-08-22 02:02 UTC
I tried to sign up and login to Snap!, but it kept saying that the servers couldn't connect. Anyone know when this will be fixed?

**Comment by brianharvey** [comment] 2017-08-22 02:20
We know that Snap<i>!</i> was unreachable today, because of an infrastructure problem at Berkeley, which is now fixed.  If you still have trouble, please tell us exactly when, and exactly what happened.  (Maybe post a screenshot.)  Thanks.

**Comment by an5rag** [comment] 2017-08-22 02:43
We're facing this issue as well. The situation is exactly as described in #1144 and #1795.

**Comment by cycomachead** [comment] 2017-08-22 02:43
Also, were you able to access Snap<em>!</em> but not login or not access Snap<em>!</em> at all?

**Comment by jh69243** [comment] 2017-08-22 02:46
Yes! Well, I need to create an account for one of my coding classes at school, and it didn't let me do so at all. I was able to access Snap! though.

**Comment by cycomachead** [comment] 2017-08-22 06:12
Thanks! The web server (snap.berkeley.edu) has been a little unstable the past few days, but hopefully that is behind us. Still looking into the intermittent cloud issues.

Closing this as a duplicate of #1795

**Closed by cycomachead** 2017-08-22 06:12 UTC
Labels: website
