### ISSUE TITLE
Cursor isn't exact in text/numeric fields in blocks

### ISSUE THREAD

**Issue by SheilaBrady** [jmoenig/Snap--Build-Your-Own-Blocks#935] opened 2015-09-17 17:26 UTC
Suggestion 1:
In the text (or number) entry boxes which are within the blocks, where I click my mouse seems to be one character to the right of where the selection cursor appears.  By this I mean if there were a numeric input box with 1234567 in it, I position my mouse between the 5 and 6 and click, and then the actual selection cursor appears between the 4 and 5.
 
Suggestion 2:
In the text (or number) entry boxes which are within blocks, when I click at the end of the number, it seems non-deterministic as to whether the cursor is then placed at the end of the string, or if the entire string is selected. For example, if I have a numeric input box with 1234567 in it, and I position my mouse to the right of the 7 and click, sometimes the cursor appears to the right of the 7 and sometimes the entire number is selected.  I'll try to get this repeatable, but maybe you can see this if you try it a bit.
 
Thanks!

I am running Snap! on a MacBook Pro, 10.10.4 on Chrome 45.0.2454.85.  I am using it in the Edx class, "Beauty and Joy of Computing" taught by Dan Garcia

**Comment by jmoenig** [comment] 2015-09-17 17:46
Hmm... I can't reproduce this, the text cursor seems to be precise for me...

**Comment by SheilaBrady** [comment] 2015-09-17 17:48
Rats, I see it happening all the time.
I’ll try to make a little movie for you.

Any other information about the system setup that would be useful to you?
-s

> On Sep 17, 2015, at 10:46 AM, Jens Mönig <notifications@github.com> wrote:
> 
> Hmm... I can't reproduce this, the text cursor seems to be precise for me...
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/935#issuecomment-141163964>.
> 

Sheila Brady
sheila@alink.net
408-218-8365

Let us cultivate our gardens

**Comment by jmoenig** [comment] 2015-09-17 17:53
Thanks! A screen capture would be great.

**Comment by jmoenig** [comment] 2015-09-18 06:00
(thinking out loud to myself...) I wonder if this may be related to #578 and #753. I'm suspecting that those could be caused by a wrong mouse-cursor offset, so this could be consistent with this observation here...

**Comment by SheilaBrady** [comment] 2015-09-18 15:51
Hi there!
Ok, the movie that I tried to send you was too big so I have it stashed in my Google Drive for your viewing pleasure.
But when I try to enter your email address to send it to you, it barfs.
Could you give me an email address that is in the more standard format like Jens@Snapbugs.com <mailto:Jens@Snapbugs.com> ?
Thanks a ton!
-s

> On Sep 18, 2015, at 8:25 AM, Sheila Brady <sheila@alink.net> wrote:
> 
> Hi Jens!
> So excited!  I got to learn a new capability of the Quicktime Player!  Here is a screen capture movie which shows the issues I was talking about.
> Hope this is helpful.
> Now I’ll go read these other bugs.
> <Mouse:cursor bug for Jens.mov>
> 
>> On Sep 17, 2015, at 11:00 PM, Jens Mönig <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> (thinking out loud to myself...) I wonder if this may be related to #578 <https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/578> and #753 <https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/753>. I'm suspecting that those could be caused by a wrong mouse-cursor offset, so this could be consistent with this observation here...
>> 
>> —
>> Reply to this email directly or view it on GitHub <https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/935#issuecomment-141353636>.
>> 
> 
> Sheila Brady
> sheila@alink.net <mailto:sheila@alink.net>
> 408-218-8365
> 
> Let us cultivate our gardens
> 
> 
> 
> 

Sheila Brady
sheila@alink.net
408-218-8365

Let us cultivate our gardens

**Comment by jmoenig** [comment] 2015-09-18 15:58
Ah, video sharing is not something Github issues supports, bummer :-(
Can you share our video via Dropbox? Or you can send it directly to me:

  jens at moenig dot org

or

  jens dot moenig at sap dot com

Thanks!

**Comment by jmoenig** [comment] 2015-09-18 17:10
Thanks for sharing the video! I'm now investigating...

**Comment by cycomachead** [comment] 2015-11-24 06:40
@jmoenig Has this been fixed with 4.0.3?

**Comment by brianharvey** [comment] 2015-11-27 01:33
fixed

**Closed by brianharvey** 2015-11-27 01:33 UTC
