### ISSUE TITLE
It can show in English or Chinese according to user's language setting？

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1297] opened 2016-07-08 07:27 UTC
![19 757z](https://cloud.githubusercontent.com/assets/20208703/16680311/2cbbb89e-4520-11e6-9225-c41e910770e4.png)

Open the browser how to automatically select the language, how to set up in the code file (locale.js or gui.js)?

**Comment by dekrain** [comment] 2016-07-08 12:22
Wait what ?

**Comment by aidiken** [comment] 2016-07-08 14:34
Open the browser how to automatically select the language, how to set up in the code file (locale.js or gui.js)?

**Comment by dekrain** [comment] 2016-07-09 10:45
How to select browser's language, right ?

**Comment by cycomachead** [comment] 2016-07-11 23:59
Basically a duplicate of #713

**Closed by cycomachead** 2016-07-11 23:59 UTC
