### ISSUE TITLE
Script logic broken after telling another sprite to move

### ISSUE THREAD

**Issue by adagioburner** [jmoenig/Snap--Build-Your-Own-Blocks#952] opened 2015-09-25 22:10 UTC
In the following example the script stops executing the "forever" loop without warning.
![snap-bug-frame-1](https://cloud.githubusercontent.com/assets/14843681/10113036/5b0dd74e-6395-11e5-8b34-7a1f4819d598.png)
![snap-bug-frame-2](https://cloud.githubusercontent.com/assets/14843681/10113045/5f7a94ac-6395-11e5-84ee-e327e407669d.png)
Sometimes it would reset the value of "speed" to zero for no apparent reason, or just hang :-1: 
(sorry I tried to attach the xml files but github disagrees)

**Comment by jmoenig** [comment] 2015-09-26 05:54
Looks like a race condition to me. You're trying to make the one 'Shapdow' sprite move to every clone at the same time...

**Comment by jmoenig** [comment] 2015-09-26 06:00
just making a single sprite follow another single one using this method works for me
http://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=Shadow&editMode

**Comment by adagioburner** [comment] 2015-09-26 06:01
Well, checking "thread safe scripts" does not really help.

Since Snap does not have any synchronization primitives to speak of, I think this kind of races are inevitable? How can one guarantee two threads are not trying to move the same sprite simultaneously?

I guess any meaningful behavior would be acceptable in this case, but crashing, stopping execution or memory trashing is not.

**Comment by jmoenig** [comment] 2015-09-26 06:04
Can you share your project (like I did mine)? I'd like to look at it. Thanks!

On another topic seeing these kinds of contraptions I sometimes regret putting in all the complicated stuff. You could try just using a broadcast and then making the Shadow react by moving to ... which sprite exactly? The same as you would in Scratch. Would that work?

**Comment by adagioburner** [comment] 2015-09-26 06:09
Will this work: https://drive.google.com/file/d/0B2Uj8EZqn2aHQkhtd1pSclJsNjg/view?usp=sharing ?

I was trying to find a simple way to detect if two clones of the same sprite touch (and if yes, which). Is that a question that gets asked a lot? :)

Thanks!

**Comment by jmoenig** [comment] 2015-09-26 06:15
Yes, that'll work. thanks! You can also simply share the project on the Snap!Cloud and pate its shared url here.

Snap (and also Scratch) currently do not support collision detection of same-breed clones.

**Comment by jmoenig** [comment] 2015-09-26 06:22
Okay, so your project actually works fine for me just out of the box without changing anything, I can't reproduce the error:
http://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=touching-test&editMode

**Comment by adagioburner** [comment] 2015-09-26 06:49
Now that does look weird. With race conditions, everything's possible, but still...
I run it in the version I dowloaded a week ago, and it fails every time. I run it online or in the version I downloaded now, and it works fine.
But there have not been any changes, have they?
BTW, it does fail for me in 4.0.2 as well -- maybe you can try that?
Otherwise I'll report if I can get a stable repro with the online version. 
Thanks!

**Comment by jmoenig** [comment] 2015-09-26 06:54
Oh, sure, I *did* fix a bug last week that might just have been the reason your script didn't work, now that I think of it!

https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/commit/88fb3581709c3910db678fd541eeda1d51fd5ab8

**Comment by jmoenig** [comment] 2015-09-26 07:08
Yep, this must the the reason, because that commit fixed issue #925 which sounds could have been exactly the problem you also ran into. I'm glad it's apparently working for you, now! Thanks!

**Comment by adagioburner** [comment] 2015-09-26 07:29
Great! Yes, it does look the same. Whew! 
I guess I was trusting a version number too much...

With respect to touching sprites of the same breed, now of course it can be implemented (e.g. see https://drive.google.com/file/d/0B2Uj8EZqn2aHeGZCamFlVVg4Mjg/view?usp=sharing . Too bad one cannot put this inside a block and forget...). I wish we didn't have to jump through hoops to get there though.  E.g. if for "touching sprite" the sprite itself didn't count, that would already be a great help.  Since it's not too much code to do on top of Snap, I guess it may be feasible? :+1:

**Closed** 2015-09-26 15:40 UTC
