### ISSUE TITLE
"combine with items of" from Tools library should check for an empty list?

### ISSUE THREAD

**Issue by plamencurso** [jmoenig/Snap--Build-Your-Own-Blocks#1087] opened 2015-12-24 09:23 UTC
problem here (getting infinite loops when i use it in a block, and "list.contains is not a function" in Opera latest version, must check Chrome too but it seems the problem is trivial - see below.

was trying to flatten a list for my TicTacToe exercise, to get a list of feasible positions, and it worked ok when there were any but looped when there were none.

What i think is "combine with items of" from the List Utilities library should check if it is passed an empty list.

Attaching an XML export of some tests i ran and a suggested fix (as .txt - GitHub wont accept .xml)

On that note - does Sharing in Save to  Cloud work, and how?  Thought i could just post a link to a shared project here.  And yes, I am very new at all this :)

And i can't begin to express my gratitude that this project exists! :)

Happy Holidays all :)
[list.contains is not a function.xml.txt](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/71612/list.contains.is.not.a.function.xml.txt)

**Comment by jmoenig** [comment] 2015-12-24 09:54
Please try to flush your browser's cache (or just to reload Snap a couple of times) to make sure your browser uses the latest set of scripts. I've introduced this bug with the first v4.0.4 release, but since fixed it again. It's possible that your browser holds on to an outdated version.

Let me know if that doesn't fix it. I've just tried reproducing this myself, but it does work me - I get an error but not what seems like a long loop.

**Comment by plamencurso** [comment] 2015-12-24 10:18
will test with clean Chrome and Opera and report how it goes.  And now i see "combine with ..." is in Tools, not List utilities, should probably change the subject of the issue?

**Comment by jmoenig** [comment] 2015-12-24 10:33
don't worry, I found "combine" :-)

Thanks for posting your test-case! I just tried it in my Opera and it works for me, i.e. it does not hang or produce an infinite loop. So, I bet you can "fix" this issue by simply reloading Snap! a couple of times in your opera which makes sure that it doesn't use the old buggy version.

**Comment by jmoenig** [comment] 2015-12-24 10:47
As for sharing: You simply save your project to the cloud, then you open the project dialog, select your project and hit the "share" button. Done! Now you can copy the url and paste it anywhere, like this:

http://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=Snow%20Globe

We're working on a one-click save-and-share solution, and on an "embed-to-another-website" feature. Stay tuned!

**Comment by jmoenig** [comment] 2016-01-03 11:07
Can we confirm that combining with an empty list does not "hang" Snap?

**Comment by jmoenig** [comment] 2016-01-08 12:48
Can we close this?

**Closed** 2016-01-08 16:46 UTC
