### ISSUE TITLE
CSV Format Weirdness?

### ISSUE THREAD

**Issue by YPIMG** [jmoenig/Snap--Build-Your-Own-Blocks#1932] opened 2017-11-14 17:00 UTC
Using "split [ ] by [CSV]" seems to give results that don't follow CSV specification. For example, single-quotes work the same as double-quotes when in fact they shouldn't do anything.
Are you guys using a different spec from _RFC 4180_?

**Comment by jmoenig** [comment] 2017-11-14 17:20
what's the issue? I got that code off StackOverflow :-)

**Comment by YPIMG** [comment] 2017-11-14 21:07
Okay, I found the [StackOverflow answer](https://stackoverflow.com/a/8497474). If you look, it's updated and says that it doesn't follow specification.
[This one](https://stackoverflow.com/a/41563966) works better, at least for me.

**Comment by jguille2** [comment] 2017-11-15 02:40
Hi @YPIMG 
Sure [current csv split implementation](https://stackoverflow.com/questions/8493195/how-can-i-parse-a-csv-string-with-javascript-which-contains-comma-in-data/8497474#8497474) does not follow [RFC 4180 specification](https://tools.ietf.org/html/rfc4180). But [this other you point to](https://stackoverflow.com/questions/8493195/how-can-i-parse-a-csv-string-with-javascript-which-contains-comma-in-data/41563966#41563966) does not either.
And certainly the rule that says _double quote_ must be scaped by another _double quote_ is not very popular.

I write down some comments... and maybe we can close this issue (is not a bug) and consider this later in other open issues like #1670 (exporting lists) to implement a robust and consistent behavior.
  - We do not have to worry about being strict with RFC4180. We are only _spliting_ a line and then, we can not implement the full protocol (for example, a data field can not have a _line break_ inside).
  - I think current _csv split_ implementation is fine. In fact, this issue reported the 'strange' behavior of _single quotes_ (are doing the same that _double quotes_). And this is not bad... Many apps (spreadsheets) let you choose the _text delimiter_
  - If you are not using intentionally _text delimiters_ and your spreadsheet don't let you choose it, maybe you will have problems with ['] characters... But you can use directly '_split by [,]_' and you will have no problem with quotes (all quotes will be plain text).
  - And if you need something more complex, I think the solution is not into the _text delimiters_ nor into _scaping characters_. The solution is choose a 'good' separator. Maybe you have data with characters like , ; " '... But you can choose an "impossible combination" (this will be different for each case... it can be more than one char)
  - As an example, I link this [project](http://snap.berkeley.edu/snapsource/snap.html#present:Username=jguille2&ProjectName=csv). I use these two blocks ('_list_ to csv by _separator_' and '_csv_ from csv by _separator_') to import/export data. I am not quoting nor scaping anything. I'll change the default ';' separator if I need it.

Finally, I insist you can close this issue... and when Snap! implements import/export into list vars (related to #1670) we can consider all the details (also into _split_ block) to be coherent with the exporting method.

Joan

**Comment by cycomachead** [comment] 2017-11-16 08:28
If we have something we're calling a CSV separator, it should just follow the spec. There's libraries that do this for a reason.  http://papaparse.com is exceptionally good and stable.

Anyway, the fact that we have to split by line first suggests that this really shouldn't be inside the split block. 

This is not a core utility of Snap<em>!</em> -- merely a (rather) useful enhancement. I don't see why we don't just build a CSV set of blocks and put them in a library?

**Comment by jmoenig** [comment] 2017-11-16 08:41
a library for parsing and encoding stuff would be very useful, indeed. But first of all, I'd like to understand the issue here. What has @YPIMG tried that didn't work or that they couldn't do, and how can we address this?

I've done a fair number of data-heavy projects myself and was using Excel to either create / export or massage data that I wanted to then process in Snap, and that's when I noticed that merely splitting by lines and commas wasn't enough. So I shopped around what what appeared to be the simplest solution with least overhead that would - in those cases that I've tried myself - always exactly do what I expected, and I added that to the dropdown. I understand that that's somewhat anecdotal, but the code looks pretty cool and elegant to me. So, again, please enlighten me about concrete issues rather than specs.

**Comment by cycomachead** [comment] 2017-11-16 08:45
One concrete issue: Snap! Requires you to split by some line.

If you're dealing with comments or text in a CSV, something like this:

```csv
User_id,user_name,location_id,date,review_text
1,michael,5,Thu Nov 16 00:43:53 PST 2017,"Hello, 

This is a cool restaurant."
```

**Comment by jmoenig** [comment] 2017-11-16 08:49
Yes, that's true, and I know about this. In fact I've been specifically searching for something that only splits a single CSV line for cells.

**Comment by jmoenig** [comment] 2017-11-16 09:01
So, is this the concrete issue at hand? has somebody tried to parse data with free-form text?

**Comment by jguille2** [comment] 2017-11-16 12:09
Some comments:
  - The original issue is clear. @YPIMG  expected that _single-quotes_ were not considered as _text qualifiers_. Then he expected that "split [I don't know] by [csv]" were fine, but it does'nt, because he must put "split ["I don't know"] byt [csv] and this will run ok.
  - I think current behavior is fine. We can use data with ['] using ["] as _text qualifier_ (like ["I don't know"] or we can use data with ["] using ["] as _text qualifier_ (like ['A man called "horse"']). And yes, we can not use ['] and ["] simultaneously on our data.
  - I suppose a lot of people use _csv exporters_ with ["] _text qualifier_ (like @jmoenig said using Excel) get a fine result. But this is because they don't use ["] into their text and so, their default _text qualifier_ is ok.
  - For me, current behavior is fine. Yes, we are spliting only _csv lines_ (not csv plain text). We can suggest that people use ["] text qualifier to use this block.
  - And if we want to go deeper into CSV parser... the _split_ block is not first step. We can resume #1670 and think about list import/export feature.

**Comment by brianharvey** [comment] 2017-11-22 03:06
No, I think this is a bug.  If we are naming a feature "csv" we are leading users to expect that they can take _any_ csv file from _any_ program or web site, and split it successfully.  If I make this spreadsheet in Excel:
<img width="203" alt="microsoft excel001" src="https://user-images.githubusercontent.com/3885074/33107807-bddaf666-ceed-11e7-93fd-a97d65da8291.png">
and ask it to save as csv, here's what I get:
<img width="236" alt="aquamacs001" src="https://user-images.githubusercontent.com/3885074/33107821-d18b5066-ceed-11e7-857d-0166bd51cdb7.png">
So we have to be able to read this file.  That's the long and short of it.

Multiline fields are a problem because Jens wants "csv" to mean "csv record" rather than "csv file."  I think that design decision should be rethought.  (For one thing, it would be great if a billion-line csv file were parsed at JS speed rather than at Snap<i>!</i> speed.)  Users expect it to mean "csv file" and it's cold comfort to be told that the manual says the right thing.

I'm labelling this both "bug" and "misfeature."  The "bug" part is that even single-line records are not parsed correctly; the "misfeature" part is that SPLIT BY CSV should parse the whole file.

**Comment by YPIMG** [comment] 2017-11-27 17:24
FFS, Github just flat-out refuses to send me notifications for anything.
Anyway, after reading this, brianharvey has already said most of everything I wanted to say. 
In my use case, I was loading spreadsheets full of text to handle around, and some boxes contained apostrophes. They were interpreted as quotes, which I wasn't expecting and thought might be important to bring up.
I'd be content with single-line CSV, since there's already a split-by-lines. But if you guys do that, can I ask that you set up a library with CSV-file support? Maybe a whole library dedicated to loading various file types. I'd even offer to make it myself.

**Comment by jguille2** [comment] 2017-11-28 13:44
Hi!

Reading the comments, I've changed my mind. And leaving aside #1670 (to implementi an import/export feature for lists) and other possibilities (to consider later), I think we must modify "CSV Split" according to RFC4180, in order to be compatible with CSV export from Excel.

Then, we need to:
  - Do not consider single quotes as _text qualifiers_
  - Consider [""] as a scaped  ["] (not a _text qualifer_).

This is the current behavior:
![csvimporting](https://user-images.githubusercontent.com/2926315/33322432-a52727d2-d449-11e7-9738-100417877027.png)

This table shows the problems with Excel export.

I never use Excel, but I have searched for a Windows computer to check this.

If you agree (@jmoenig, @brianharvey ), I can make a PR with a fix to this behavior. Right?

Joan

**Comment by brianharvey** [comment] 2017-11-28 16:45
Yes, that would be great, but first, what are we doing about the multi-line cell case?  That has to be caught _before_ splitting by line.

My vote is that split by csv should work on the entire file, not on one line.  Jens?  Are you okay with that?

**Comment by jguille2** [comment] 2017-11-29 07:28
I wait for your decisions...

Only comment I think that for now it is better to implement only the fix (spliting only a csv line) that is clear according to be full compatible with spreadsheet exports. After this, we will still have pending #1670 about a consistent import/export list feature... and we will have to decide different details: supporting to _break lines_ into a field, square requeriment (imposing the same number of fields in each row or not), behavior of csv file with only a line (a list or a list of list (with only one list))...

And you know the importance of this new feature will be the direct import/export of lists (saving and loading lists from a file) then, user will not have to worry about csv format anymore.

**Comment by cycomachead** [comment] 2017-11-29 07:41
I'm going to say something controversial... I don't think CSV handling belongs in Snap!.
We should handle that in a library, one that just uses JSFunction and can convert things as needed. 
(And it could even install some handling to augment code w/ context menus if desired...).

BH is right, that we want a function that handles an entire CSV file. Since this is the case, using `split` doesn't make much sense. There's no other way that split would return a 2D list from normal use, and so I don't think the semantics of the block really make sense to work with a whole CSV file.

As far as import/export of lists: I don't think CSV should be seen as the solution there. For one thing, it's still multiple steps over what would be necessary (requiring `split` to import). More importantly, CSVs can only correctly encode a 1 and 2D array of text, a subset of what would be represented by Snap! Lists.

**Comment by jguille2** [comment] 2017-11-29 09:50
Hi @cycomachead ,

I agree with your comments in the sense we need to think more about this (general import/export features). You are right that CSV is only for 2D list... but anyway we know that it is a very powerful tool for users.
You can use an XML or JSON format for a full import/export action (using this files like Snap data). But if you want to use these files in other contexts, you need more skills to use them. In the other hand, everyone knows how to open a spreadsheet an begin to play with CSV data. We applied #1670 into Snap4Arduino (in the past May version) because many teachers request us this feature (to read sensors and later work with this data in a spreadsheets).

Anyway... I think we must combine different "work lines". We can fix concrete issues on current features (like this _split by csv_) and work more thoroughly and calmly with the new implementations.
In this sense, I vote to fix [split by csv] to use csv lines... and we'll continue in other thread.

**Comment by jguille2** [comment] 2017-11-30 05:25
Hi,

I know that PR specifications are not yet blessed... but it is the way to document it (I'll forget it right away) and then you can test it.
The PR follows RFC 4180 specs and, the most important, offers full compatibility with spreadsheets.

I have been doing an express learning with regular expressions ... :sweat: ... and I have been able to simplify the code :satisfied:

**Comment by cycomachead** [comment] 2017-11-30 05:52
Do we really need to regex to parse these? I feel like a simple loop is probably faster. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment] 2017-11-30 09:59
I think that lots of data from web sites is downloadable as csv, so we're going to be dealing with them forever.  And also, what are we going to do, convert xslx to lists?  Do we even know how to read those?  If what we have is a user-created list, yes, we should be able to export it and then later import it without intermediate formats.  But that's pretty much independent of the spreadsheet issue.

I guess "we almost handle csv data except for this one case" is better than "we get lots of cases wrong," but it's still not as good as "we handle csv 100% correctly."

It's true that splitting the entire file is sort of an abuse of SPLIT, which otherwise only works on one-dimensional things.  It wouldn't kill me to have a library, as Michael suggests.  But then we don't need split-by-csv at all.  On the other hand, why does split have to be so uniform?  Because the JS one is?  We're already past that point with the single-line split-by-csv.  I don't mind having complicated domains and ranges, as long as the result is to "do the right thing" in all cases.  (We've talked about APLifying the math functions.)

If the csv is generated by Google Forms, there's every reason to expect multiline cells, by the way.

**Comment by jguille2** [comment] 2017-11-30 10:56
...
As I said, I agree with a full CSV feature... but I think we can step forward dynamically (fix this issue, think about CSV feature into a lib or into an import/export dialog on vars...)
Anyway, I'll make a code to do the full split to test and continue advancing...

**Comment by cycomachead** [comment] 2017-11-30 11:23
This is why people build libraries. We should just have a data formatting library. There's plenty of tools to handle XLS(X) files but we definitely shouldn't build that stuff natively into Snap!.



> On the other hand, why does split have to be so uniform?

I don't think it _has_ to be so uniform, but it feels weird to my have some special domain and ranges just for 1 item in a dropdown. Maybe it is the intuitive thing, and it's not so bad, but then I'd be left wondering how to do that we other input to the split block. Splitting by a single line, IMO, is still (mostly) within the understandable domain and range of SPLIT since you get a 1D list. But, I think it's overcomplicating what you'd expect a SPLIT function to do anyway. 
🔥 No one should ever write a regex like the one currently being used, especially not in JS... I might tolerate a nice multi-line Perl regex that is clear about what's trying to be done... And it's impossible to understand the performance of such a complicated regex. 🔥 

Also, the reason I think we should handle CSV as a library is because we should not write a CSV parser ourselves and we shouldn't load nor parse that code until it's needed.

**Comment by brianharvey** [comment] 2017-11-30 18:09
Well, I think we all understand each other, and it's up to Jens to decide both about the feature and about the programming style.

**Comment by cycomachead** [comment] 2017-11-30 21:47
My point isn't so much about programming style, but that we really should think about where it makes sense for us to spend time and what places require care.

We can iterate on update libraries more easily than the rest of Snap! And they are easier to support in the future, since deprecating stuff is hard.

**Comment by jguille2** [comment] 2017-12-01 13:17
I don't want to be too heavy on this... and just share and write down the last comments.

  - I've made a block to import CSV according to standards (and also to spreadsheets performance). It is only a draft to play and document possibilities for a lib or for an import feature.
[csvImportBlock.xml.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/1521143/csvImportBlock.xml.zip)

  - This code follows the standards with two considerations:
    - [RFC4180](https://tools.ietf.org/html/rfc4180) imposes square arrays (the same number of fields) and this not. We are only importing and so, standards are fine... and this accepts non-square arrays.
    - I use for _line breaks_ (CRLF) the same we are using on [split by line] to accept W$ performance (\r\n). This is the agliest aspect of the regexp (with the _/\r\n|[\n\v\f\r\x85\u2028\u2029]/_ you are using).
  - Then, I think the result is fine
![csvresult](https://user-images.githubusercontent.com/2926315/33479125-3755b27e-d68c-11e7-87df-79b7f16fb3bb.png)
  and see it respects the _line breaks_ inside the fields
![csvbreakresult](https://user-images.githubusercontent.com/2926315/33479185-7852fe26-d68c-11e7-9410-ec5dd25686f0.png)
  - And if you think these codes are usable, I can split the regexp code to document the meaning of each part of the expression.

I insist this is only a draft... If you think it is interesting, I will review it later and check all the cases...

And, of course, I will follow your directives. We can make a csv lib with different tools, or implement another split option (by csv_line and by csv_file), or implement later a list import/export feature (related with #1670), or put it aside with any problem...

Joan

**Comment by brianharvey** [comment] 2017-12-01 18:32
@jguille2 Your work is always thorough and terrific.  I would pull it, but it's up to Jens.

The only point I want to insist on is that spreadsheets and lists are two separate issues.  When we later work out how to handle export and import of lists (which I would do in the same xml format in which they are saved as part of a project, so as not to duplicate work), that won't eliminate the need for a tool to import csv data.

**Comment by jguille2** [comment] 2017-12-03 02:19
Thanks for your words, Brian.
I update the [list from CSV] block. I've fix an issue with possible first empty lines and change de validation method.

[csvImportBlock.xml.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/1524429/csvImportBlock.xml.zip)

Ok. Then it's your turn. 

I can update the PR with this block (changing the _line csv spliter_ for a _full csv spliter_), or add two options into the _split_ block, or leave aside _split_ block and consider this as a lib (then I'll make another [CSV from a list] to do the export operation)... or we can stop now an we can consider this later.

Respect your last comment... It's clear list import/export must be in other format (xml or json) to save/load data from Snap! That is the right way. Yes, lists are more than a 2D square table!! But CSV import/export (especially the export) will remain interesting... to be able to use data outside Snap (as with a spreadsheet).

**Comment by jguille2** [comment] 2017-12-04 23:27
Hi!
In the meantime, I've build a block for the _export_ operation... and thinking in a "_csv lib_" some other blocks to manage data. The idea is to help a user that plays with data using also a spreadsheet and maybe he does not control list (and list of list) operation.
A first draft of these blocks would be:

![csvblocks](https://user-images.githubusercontent.com/2926315/33581574-a2069ce2-d951-11e7-8c9d-c470c1b442ea.png)

You can see a [demo](http://snap.berkeley.edu/snapsource/snap.html#present:Username=jguille2&ProjectName=csvWorkingProject) and test import and export operation.

This is a multi purpose feature... and there are many options to choose! If you think this is interesting, I can document more details and debate about them.

One question. I've seen Excel use (by default) the _regional settings_ to determine the _list separator_. And then, in some locales, it uses _semicolons_ instead _commas_. Do you think we must consider this? I can change the block with another slot to choose _separator_ [, or ;].

**Comment by brianharvey** [comment] 2017-12-05 01:46
Yes, this is a great idea!  I haven't had time yet to play with it, but it definitely fills a need.

How come there's just the one command among the otherwise wonderfully functional library?

> semicolons instead commas
I hate computers.

I suppose it depends on whether it's one tiny region or, you know, all of Europe, like switching the meanings of period and comma in long numbers.

**Closed** 2018-01-19 14:18 UTC
Labels: Jens?, bug, cat: operators, misfeature
