### ISSUE TITLE
Codification blocks show in search even if codification is disabled

### ISSUE THREAD

**Issue by gdavid04** [jmoenig/Snap--Build-Your-Own-Blocks#2111] opened 2018-06-04 14:29 UTC
Codification blocks show in search even if codification is disabled.
![image](https://user-images.githubusercontent.com/25725819/40923167-5c04b088-6814-11e8-8c80-8091a4154c3e.png)

**Comment by cycomachead** [comment] 2018-06-24 05:57
Duplicate of #898

**Closed by cycomachead** 2018-06-24 05:57 UTC
