### ISSUE TITLE
issues with color palette

### ISSUE THREAD

**Issue by jowede** [jmoenig/Snap--Build-Your-Own-Blocks#739] opened 2015-03-08 11:03 UTC
Sorry about simple questions of a newbie ... I want to set the pen color by a number. Reproducing the info of the Help window shows a dissenting behavior. Color range is not as in the example (left).
![helpexample](https://cloud.githubusercontent.com/assets/11311911/6545476/75d9a4b8-c589-11e4-952b-60476f2827ee.png)
Changing the number explicitely to 130 does not show blue as expected, but the previous example(right).

Would it be possible to set color by RGB-values?
And is it possible to set the screen background color in a similar way?

Thanks for help.

**Comment by jmoenig** [comment] 2015-03-08 11:17
Funny. This seems to be a bug. I'll research into this and fix it. Thanks for reporting it!

In the meantime, here's a project demonstrating how the "Scratch" part of colors is supposed to work:

http://snap.berkeley.edu/snapsource/snap.html#cloud:Username=jens&ProjectName=Colors

And here's another one showing how you can use this mechanism for rgb colors:

http://snap.berkeley.edu/snapsource/snap.html#cloud:Username=jens&ProjectName=rgbMixer

**Comment by jmoenig** [comment] 2015-03-09 09:37
So, it appears that there isn't a bug, but the help-screen (which is taken from Scratch 1.4) is inconsistent with Snap's color model.

I thought that setting the pen color to a numerical value was broken (hence the "bug" assumption), but that seems to work fine as of just now. However, the help screen indicates a range of more than 100, while, in fact, in Snap it is *exactly* 100. Apparently Scratch (at one time) had a color range of 200, which is somewhat inconsistent with other ranges in Scratch being mostly from 0 to 100 (size, volume).

**Comment by jowede** [comment] 2015-03-10 18:29
Thanks, the demonstration project confirmed my understanding, what is going on.

May be another unclarity can be explained in a similar way: After setting the pen shade to 100 the pen should be white. But it is red. 
![penshade](https://cloud.githubusercontent.com/assets/11311911/6582038/d0352dc4-c75a-11e4-8c1f-6a505bf4a322.png)

Also, in this color model the color black is missing and grey tones are not possible, because i.e. a shade of 50 always shows a shaded color, as black has not his own number. The same applies for white.

**Comment by cycomachead** [comment] 2015-12-02 01:58
Though this is older, I'm tagging a duplicate of #897

**Closed by cycomachead** 2015-12-02 01:58 UTC
Labels: cat: pen, duplicate, help / manual
