### ISSUE TITLE
Snap!Cloud storage is down.

### ISSUE THREAD

**Issue by davidrhmiller** [jmoenig/Snap--Build-Your-Own-Blocks#1952] opened 2017-12-02 19:17 UTC
This likely isn't the place to report this bug, but I haven't yet found a better reporting/escalation channel.

The Cloud storage feature stopped working sometime in the last few days. Even though there are multiple mirror servers for Snap!, they all seem to rely on the same cloud storage backend. I can't load anything from Cloud storage, whether the examples on the main site http://snap.berkeley.edu/ or my own personal projects.

The "Open..." menu option fails with a dialog box reporting the error: "could not connect to https://snap.apps.miosoft.com/SnapCloudPublic"

I get the same dialog box error from any of the "present" links, e.g.

http://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=tree%20animation

http://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=Menuet
http://snap.berkeley.edu/snapsource/snap.html#present:Username=davidrhmiller&ProjectName=Lesson%204.3%20Lab

Since the problem is likely on the miosoft end, the feature request here is to offer users guidance on what escalation path to follow when this happens. I've never heard of miosoft, don't know whom to contact to report the problem or to learn about the status of resolving it.

davidrhmiller@gmail.com
<img width="331" alt="screen shot 2017-12-02 at 1 54 21 pm" src="https://user-images.githubusercontent.com/18092530/33518954-75702a82-d76b-11e7-816c-82386efe8133.png">
<img width="1434" alt="screen shot 2017-12-02 at 1 53 48 pm" src="https://user-images.githubusercontent.com/18092530/33518955-757e1b4c-d76b-11e7-8aed-d7ea20c4f232.png">

**Comment by brianharvey** [comment] 2017-12-02 20:05
Duplicate of #1951

**Closed by brianharvey** 2017-12-02 20:05 UTC
