### ISSUE TITLE
Comments for rest of control block are deleted when a block is deleted

### ISSUE THREAD

**Issue by sharived** [jmoenig/Snap--Build-Your-Own-Blocks#796] opened 2015-05-08 02:29 UTC
Here is my example.
![before](https://cloud.githubusercontent.com/assets/1163591/7529505/d26d587a-f4ee-11e4-8d71-5dec21cd4ddd.png)

I then remove the first move block - all comments below this will be deleted

![after](https://cloud.githubusercontent.com/assets/1163591/7529509/f2a5753c-f4ee-11e4-8d46-5b0fcd5bb1e3.png)

This seems to only happen within the control block, so anything outside of the loop is fine.

Let me know if this isn't clear.

**Comment by sharived** [comment] 2015-05-08 02:51
Also another comment issue I had was that certain comments would not save.  I see them in my project, save it and open the project in another window and they aren't there.  I can't seem to reproduce this consistently, but thought I'd let you know.

**Comment by sharived** [comment] 2015-05-08 03:07
Maybe I am seeing a pattern here for the 2nd issue.  The blocks which had comments that wouldn't save were all associated with  custom blocks.
![example](https://cloud.githubusercontent.com/assets/1163591/7529824/45e1830e-f4f3-11e4-995d-0210ba78f920.png)

This is a screen shot
![screen shot 2015-05-07 at 7 59 01 pm](https://cloud.githubusercontent.com/assets/1163591/7529840/89a8c23c-f4f3-11e4-968f-4dbf63f17189.png)

So after typing them in again they are saving, but as you can see something is definitely different when attaching comments here.

Also sometimes comments are part of the script pic and sometimes they are not.  Again haven't figured out a pattern here.  But you can see in the above example.

**Comment by jmoenig** [comment] 2015-05-08 05:18
Hi Shari. Yep, it's a bug, good catch!

**Comment by cycomachead** [comment] 2017-02-12 09:26
Closing this. The first issue of deleting comments was fixed recently, and the second issue is a duplicate of other issues.

**Closed by cycomachead** 2017-02-12 09:26 UTC
Labels: bug, duplicate
