### ISSUE TITLE
Move custom blocks in library up or down

### ISSUE THREAD

**Issue by liam4** [jmoenig/Snap--Build-Your-Own-Blocks#1026] opened 2015-11-22 10:07 UTC
As it is if I make custom blocks they get added to the custom block section of the category at the bottom. I'm suggesting when you context-menu the block you have the option to move the block up or down. This would be very useful for organizing libraries.

**Comment by brianharvey** [comment] 2015-11-22 16:57
Duplicate of #271.

**Closed by brianharvey** 2015-11-22 16:57 UTC
Labels: duplicate

**Comment by liam4** [comment] 2015-11-22 17:44
Oops :P
