### ISSUE TITLE
"when I receive ..." drop down doesn't list messages from within custom block definitions

### ISSUE THREAD

**Issue by danyoel** [jmoenig/Snap--Build-Your-Own-Blocks#1456] opened 2016-10-11 16:01 UTC
When the broadcast block is used, that block's message gets added to the list of messages. If a broadcast block is inside a custom block, then that message does not get added. I think this is by design; the broadcast is scoped to the block.

However, a script _outside_ the block that uses "when I receive any message" still triggers when the block fires the broadcast.

Bug?

http://snap.berkeley.edu/snapsource/snap.html#present:Username=danyoel&ProjectName=broadcast%20scope

**Comment by dekrain** [comment] 2016-10-11 16:14
Any hat except Block Hat doesn't work inside block definition

**Comment by jguille2** [comment] 2016-10-11 16:39
Testing, I see 'message' is a global.

Even when I send a message to some sprites...
![broadcastblock](https://cloud.githubusercontent.com/assets/2926315/19279495/f003969e-8fe1-11e6-8657-062cddb7fe69.png)

 I can evaluate actual (last) message from every sprite.

**Comment by jmoenig** [comment] 2016-10-11 16:42
good point, @danyoel !

Broadcasts are by default global in Snap, and they can be triggered from within custom blocks. That part is intentional. When populating the drop-down menu of available messages - either in one of the ```broadcast``` commands or in a ```When I receive``` hat block I'm scanning the scripts of the whole project for those blocks, but I am *not* scanning custom block definitions. Thought I'd get away with it :-D

Thanks!

**Comment by jmoenig** [comment] 2016-10-11 16:45
Yep, @jguille2 , ```message``` is global and it always reports the "last" message. This is not the world's greatest abstraction, especially now that we're experimenting with local sends (whose user interface currently is really just experimental and totally un-intuitive, let alone discoverable). The ```message``` reporter is also prone to all kinds of race conditions...

**Comment by danyoel** [comment] 2016-10-11 17:09
Looks like the broadcast behavior is by design. The bug is in the `when I receive` drop down list population. Thanks @jmoenig

**Comment by brianharvey** [comment] 2016-10-11 17:41
Not that this is urgent, but the right thing to do about timing problems with MESSAGE is to take "any message" out of the pulldown and have a separate block WHEN I RECEIVE ANY (message), in which the (message) part is an upvar.

**Comment by jmoenig** [comment] 2016-10-12 09:54
Thanks, @danyoel ! I have patched my current dev version with a fix that also scans custom block definitions for broadcasts and includes those in the messages drop down menu. You should be able to test the intended behavior for your test project here:

http://snap.berkeley.edu/snapsource/dev/snap.html#cloud:Username=danyoel&ProjectName=broadcast%20scope

This fix will be included in the next release.

**Comment by cycomachead** [comment] 2016-11-14 21:59
Was this released pushed? (I think so?)

**Comment by jmoenig** [comment] 2016-11-15 06:59
yep, it's in the current stable release. Thanks for checking up on this.

**Closed by jmoenig** 2016-11-15 06:59 UTC
Labels: bug, fixed in next version
