### ISSUE TITLE
Pasted Newline Characters Multiply

### ISSUE THREAD

**Issue by J0SLAN** [jmoenig/Snap--Build-Your-Own-Blocks#1128] opened 2016-02-05 23:57 UTC
Sometimes, when you paste text into a block input that shows newlines (Like the JS block), and the thing you pasted has newline characters, after saving and reopening a project the newlines multiply themselves. Looking at the end of each line shows a random space character, and deleting that character stops the multiplying. I've only been able to reproduce this myself on my Win10 desktop.

**Comment by J0SLAN** [comment] 2016-02-07 20:47
Turns out it happens even without copy/pasting.

**Comment by jmoenig** [comment] 2016-02-07 22:13
this must be specific to some platform I don't use...

**Comment by liam4** [comment] 2016-02-07 22:39
Not an issue for me - Chrome 50 on OS X.

**Comment by J0SLAN** [comment] 2016-02-09 15:25
Yeah, I'm pretty sure it's only on Windows. When I get home I'll check if it depends on the browser. I can't get it to happen on my Chromebook.

**Comment by brianharvey** [comment] 2016-02-13 00:55
Duplicate of #1106.  Closing.

**Closed by brianharvey** 2016-02-13 00:55 UTC
Labels: duplicate
