### ISSUE TITLE
"Exports all scripts as pic...", when it fails, makes the project unrecoverable

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap--Build-Your-Own-Blocks#883] opened 2015-07-23 14:52 UTC
As a sample, load 
tinyurl.com/bjcjeopardy (which only has 5 blocks or so I wrote)
and try it (shift-click "file")

In Chrome, it replaces my tab with the Snap! IDE with a "Aww, Snap!" page, and clicking "back" returns to an _empty_ Snap! window, so all changes before saving are immediately lost.  It feels like if we know that's a possibility, we should warn them to save before they proceed.

For the Advanced Placement CS Principles Create Performance Task, students have to submit a PDF of their code, so ALL students using Snap! in CS Principles could use this feature (potentially thousands of kids a year).  I'd hate for even one to lose their work as the result of this sharp-edged feature.

**Comment by jmoenig** [comment] 2015-07-23 15:15
Hey, Dan, that's an *experimental* feature which is *hidden* and marked *red* for a reason! ;-)

Okay, it's not "*only 5 blocks*" long, but it has all *many, many* custom block definition. You can export it currently in Firefox, and it generates a 808 x 10425 pixel bitmap (that's pretty huge):

![jeopardy](https://cloud.githubusercontent.com/assets/2596285/8854075/564246e6-315e-11e5-9114-9f3be8f9b2e7.png)

**Comment by cycomachead** [comment] 2015-07-26 19:58
@jmoenig @ddgarcia 

This is the _same_ Chrome bug that I mentioned in an email a week or so ago, and that has been for a long time. 

Can we revive #433 / #537 ? I can fix the error message to be more verbose, like the one that appears for tainted images.

**Comment by jmoenig** [comment] 2015-07-26 20:08
afaik this is beyond our (reasonable) control...

**Comment by cycomachead** [comment] 2015-07-26 21:37
> afaik this is beyond our (reasonable) control...

Not entirely, look at #537 -- it's entirely possible to catch before exporting. There is no ~good~ easy solution to being able to actually export / save the picture in Chrome, but it should be worth _preventing_ people losing work. 

There are other option which exist to work around this issue.
* use the Blob API and create ZIP files, which don't seem to have this issue. (At least as far as I've read. I haven't implemented this in Snap<i>!</i> or anything.)
* There is a FileWriter API which is deprecated but works in Chrome
* Chrome specific code could potentially request additional permissions which would allow direct file system access.

**Comment by brianharvey** [comment] 2015-07-26 23:36
+1 for fixing this showstopper problem, even if kludgily.

**Comment by lmock** [comment] 2015-07-27 00:15
+1 this has been a problem for far too long and is extremely frustrating for students. if this can help not make students feel this way I'm all for it.

**Comment by jmoenig** [comment] 2015-07-27 04:13
So, does anybody know what the problem is and how to fix it?

**Comment by brianharvey** [comment] 2015-07-27 04:36
Michael says #537, which is a workaround, not a fix -- for that we have to rewrite Chrome.  But a workaround is important in this case.

**Comment by cycomachead** [comment] 2015-07-27 04:47
> So, does anybody know what the problem is and how to fix it?

Exact problem is opening a URL in Chrome that is > 2.09 million characters. The is a known Chrome thing which Google isn't going to fix due to "security" reasons. When Chrome encounters a URL that is clicked / activated (either via the user or JS) then it essentially crashes the current process. Interestingly, opening a _new_ tab, seems to crash the process from which that tab originated in addition to the new process that would be created. I don't know if this would be a bug or not, but that part is definitely out of our control. 

So, what can we do?
  Never open long URLs in Chrome. 

That's easy to catch though! #537 does it, I'll fix merge conflicts. I'm also going to test on non-Chrome browsers that still use Blink, like Opera. I don't have android to test, but that would be good to do. 

Otherwise, for a good fix we need something like JSZip. Which we should do anyway. The current practice of presenting XML is poor for many users and zip files aren't downloaded in any browser. (And can actually be saved on iOS to apps like dropbox.) I'd be happy to work on this -- it wouldn't be hard but would introduce an external library.

**Comment by jmoenig** [comment] 2015-07-27 05:14
See, I'm not convinced just "not opening long URLs in Chrome" fixes the problem, because that's precisely what the "save to disc" feature did, and it also crashed Chrome. So, my question is, rather than having a vote on this, do we *know* why Chrome crashes? Can we issue a bug report with the Chrome developers?

You don't have to doctor the pull-request, it's easy to enough to understand what it does, but I'm asking does it fix or even workaround anything at all? And - rather than tell people that what we want to do isn't possible, how can we make it work.

What I hate about the current "solution" proposal is that it's not even a solution, it tells people to use a different browser for stuff they already have in Chrome and can't save. That sucks.

**Comment by jmoenig** [comment] 2015-07-27 05:33
Also, an external library is out of the question. BUT, we can find out what they do to circumvent this problem, and do the same!

**Comment by cycomachead** [comment] 2015-07-27 05:42
The problem with Save to Disk is that, we were still creating URLs and clicking them, just not opening them. So, the problem in Chrome isn't a display issue, it's an internal issue. And yes, there are bug reports, but they aren't going to be fixed according to the Chrome team. 

I can try to find the issue.

As far as external libraries -- no one gets around the URL issue, but zip files aren't treated the same way. I personally feel like it's worth using zip files but that solves the XML display issue. (Also it's not worth any of our efforts to re-write an XML library.)

**Comment by brianharvey** [comment] 2015-07-27 05:47
I think we should just not make such long URLs.  That was a brilliant workaround by Nathan back when saving to the cloud was unreliable, but there is no longer any need for it.  Am I missing something?

**Comment by jmoenig** [comment] 2015-07-27 05:55
Wait. JS doesn't have file access, so any external ZIP library must know something we don't, because surely the zip file data must be allowed to exceed the "limit".

I can't believe Google are crashing Chrome "on purpose" instead of just popping up a dialog box. I mean, that's like trying to fight a suicide commando...

**Comment by cycomachead** [comment] 2015-07-27 06:01
> I think we should just not make such long URLs. That was a brilliant workaround by Nathan back when saving to the cloud was unreliable, but there is no longer any need for it. Am I missing something?

So, this isn't possible without a server or without something like using zip files. 

We still need a way to export content locally. In theory, we can try to use use `data:application/octet-stream;...` before saving a file but that likely won't work because it often messes up the file type so that users would have to know to type ".png" or something. 

The Blob() API might actually solve problems as it seems that the URLs it creates a pointers, but I don't know for sure how they work across new tabs, or if they very by length of content. I'm going to read the ECMA spec for this, and I'll post what I find. 
https://developer.mozilla.org/en-US/docs/Web/API/Blob

In the mean time, these features are problematic _only_ in Chrome. The good thing about Chrome is that every (desktop) Chrome user, always has at least one other browser that doesn't have this issue, since Chrome isn't included as a default browser on OS X, Windows or even Ubuntu. (Recent Android OSes may be a problem...).
Because of this, we can always direct people to try a different browser and they'll have a way to get content out

**Comment by brianharvey** [comment] 2015-07-27 06:04
Oh.  Can we generate a message while the project is still small enough to save?  And also, when we integrate Kyle's autosave feature, is that going to crash Chrome?

**Comment by jmoenig** [comment] 2015-07-27 06:09
Brian, yes, you are missing something. We *already* don't update the URL with long data stuff unless the user explicitly wants to (it's an option in the setting menu that's ```off``` by default. I've pulled Michael's pull-request. Here, we are talking about something different.

Grrr... don't participate in the wrong discussion!!!!

*This* issue is about *Dan wanting students to use a _disabled_ feature* (which is *disabled* because we *know* it leads to problems!!!) and then complaining about those exact problems that made us essentially *take out* the feature.

**Comment by jmoenig** [comment] 2015-07-27 06:12
I can't believe Google does this on purpose. I just don't believe it. It's a bug, obviously, because no other browser behaves that way. It's their job to fix it. don't half your graduates work with Google anyway? :-)

**Comment by cycomachead** [comment] 2015-07-27 06:12
> Oh. Can we generate a message while the project is still small enough to save? And also, when we integrate Kyle's autosave feature, is that going to crash Chrome?

We should only generate a message on export. To know if an error is going to occur we need to serialize whatever is trying to be exported, so we can pretty much only catch the issue just before it occurs, but that's fine! We don't need to scare users who only use the cloud.

As far as autosave -- I don't know how it's impleted, but no. The crashing applies to accessing a URL in someway. Autosave should access the cloud, or use local storage. Local Storage has a 5MB limit, (which is really a 2.5MB due to UTF-16 issues, but that could be worked around to get back to 5MB).
There are other app-specific work arounds for local storage, but they likely aren't worth the effort.

**Comment by cycomachead** [comment] 2015-07-27 06:13
> I can't believe Google does this on purpose. I just don't believe it. It's a bug, obviously, because no other browser behaves that way. It's their job to fix it. don't half your graduates work with Google anyway? :-)

I mean, the security concern is somewhat legitamate, though they definitely should warn users instead of killing a process. (At the same time though, we are pretty much abusing URLs.)

**Comment by cycomachead** [comment] 2015-07-27 06:17
> This issue is about Dan wanting students to use a disabled feature (which is disabled because we know it leads to problems!!!) and then complaining about those exact problems that made us essentially take out the feature.

Wait, we are _also_ talking about exporting a project. Despite fixing the URL issue, exporting a project still crashes the current process. 

Images are also URLs. And this issue could still occur when someone has enough code in a single block / scripting area. It could occur if they export a pic of a large costume potentially, or really export anything from within Snap<i>!</i>.

**Comment by jmoenig** [comment] 2015-07-27 06:28
So, in this document:

https://developer.mozilla.org/en-US/docs/Web/HTTP/data_URIs

it says that "Although Mozilla supports data URIs of essentially unlimited length, browsers are not required to support any particular maximum length of data. For example, the Opera 11 browser limits data URIs to around 65000 characters."

I don't think that allows them to simply crash. Also, it would be really helpful if browsers somehow made their size restrictions somehow public, via an API.

Okay, so we don't want URLs at all, if they aren't guaranteed to work. We need an installable app that integrates a little HTTP server that Snap can talk to, if it's there. This app will handle all export stuff and also give us file access etc. I guess we could use node.js or Python to make it "platform independent". Should be easy, right? Who's in?

**Comment by jmoenig** [comment] 2015-07-27 06:34
Another question would be to find out how the zip people are circumventing this problem. If they can do it without either a URL or a companion app, we should, too.

**Comment by cycomachead** [comment] 2015-07-27 06:38
Ok, before we go down the app route -- 

1. We can still avoid this issue. Why can't we have a solid fix that prevents anyone from losing work? 
2. We still need to have support in places where a "companion app" isn't avaiable.

We should _never_ lose anyone's work!

As far as a _companion_ app, I'm in. 200%! I've actually toyed around with simple ones because we c currently could use it for a variety of reasons, and a companion app would allow other features, like native reading of fles. However, I **strongly** feel that this is a companion to Snap<i>!</i> and an enhancement of functionality. 

Background links:
http://stackoverflow.com/questions/16761927/aw-snap-when-data-uri-is-too-large
   It appears, that blob URLs don't suffer the crash problem, which confirms my hunch but defineitely needs testing. 
http://stackoverflow.com/questions/8748362/chrome-crashes-when-uri-is-too-long
   Suggests JSZip (which is probably doing the Blob thing...I'm currently still reading the source.)
https://code.google.com/p/chromium/issues/detail?id=44820
   Chrome bug...
https://code.google.com/p/chromium/issues/detail?id=69227
   Dupe of the above...
https://code.google.com/p/chromium/issues/detail?id=130967
   More...
https://code.google.com/p/chromium/issues/detail?id=236348
  Just because I also had this open. :P

**Comment by cycomachead** [comment] 2015-07-27 06:40
> Another question would be to find out how the zip people are circumventing this problem. If they can do it without either a URL or a companion app, we should, too.

I think JSZip is actually using another plugin called FileSaver.js which gets around some issues, but now I'll need to figure out what they're doing. (Likely a combo method of Flash + deprecated APIs + Blobs + other hacks)

**Comment by jmoenig** [comment] 2015-07-27 06:48
Thanks for those links, Michael! The "recommended workaround" apparently is the Blob URI, which sounds like it could be worth exploring...

**Comment by cycomachead** [comment] 2015-07-27 06:50
> Thanks for those links, Michael! The "recommended workaround" apparently is the Blob URI, which sounds like it could be worth exploring...

Yeah, so far from my reading of the spec, we should be good. 

I've been looking at FileSaver.js which is quite popular and it's main method is actually blobs! Which is good news. Apparently, things top out around 500MiB, but if some student hits that limit...well...they're on their own. 

https://github.com/eligrey/FileSaver.js/

**Comment by jmoenig** [comment] 2015-07-27 06:53
Yay! I've also been reading some of those links, and it appears that this is even a solution that'll work across all current major browsers, even IE. Looks like we can actually *solve* this!

**Comment by jmoenig** [comment] 2015-07-27 06:55
Would you like to give it shot, Michael? I can also do some experiments, but it seems like you're the right person for this, since you've found this out...

**Comment by cycomachead** [comment] 2015-07-27 06:57
Yeah, I'll take this on. I don't think this will be a super quick fix or anything, but I should be able to work it out.

**Comment by jmoenig** [comment] 2015-07-27 07:00
Excellent, thanks!

What do you think, should we continue with the current v4.0.2 release, or would it make sense to wait for the Blob URI workaround to be included?

**Comment by cycomachead** [comment] 2015-07-27 07:02
> What do you think, should we continue with the current v4.0.2 release, or would it make sense to wait for the Blob URI workaround to be included?

Continue! This is by no means a new issue, and the advantages of 4.0.2 are super nice. I think I've been telling everyone about keyboard support for a week now, and have demoed it at least a few times.

**Comment by jmoenig** [comment] 2015-07-27 07:06
Great. Thanks for a terrific discussion this morning and fruitful research, Michael! Now I'm excited about totally solving the export issue instead of crippling Snap! Yay!

**Comment by brianharvey** [comment] 2015-07-27 15:03
Oh.  Sorry.  Glad you guys settled it.

**Comment by jmoenig** [comment] 2015-07-27 15:11
Nothing to apologize for. Seems like Michael found a workaround that'll actually let us export everything same as we are doing now except it won't crash Chrome, in other words, a *real* solution!

**Comment by cycomachead** [comment] 2015-11-17 12:13
Also tagging #983 And closing since that will solve this problem.
(And adding this to my test cases!)

**Closed by cycomachead** 2015-11-17 12:13 UTC
Labels: duplicate, error handling, important
